// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NSQProtoMsg.proto

package com.youzan.sz.test.nsq.protobuf;


public final class NSQProtoMsg {
  private NSQProtoMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NSQDemoProtoReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:java.nsq.protobuf.NSQDemoProtoReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 sex = 1;</code>
     */
    boolean hasSex();
    /**
     * <code>required int32 sex = 1;</code>
     */
    int getSex();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated int64 shopId = 3;</code>
     */
    java.util.List<java.lang.Long> getShopIdList();
    /**
     * <code>repeated int64 shopId = 3;</code>
     */
    int getShopIdCount();
    /**
     * <code>repeated int64 shopId = 3;</code>
     */
    long getShopId(int index);
  }
  /**
   * Protobuf type {@code java.nsq.protobuf.NSQDemoProtoReq}
   */
  public static final class NSQDemoProtoReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:java.nsq.protobuf.NSQDemoProtoReq)
      NSQDemoProtoReqOrBuilder {
    // Use NSQDemoProtoReq.newBuilder() to construct.
    private NSQDemoProtoReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NSQDemoProtoReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NSQDemoProtoReq defaultInstance;
    public static NSQDemoProtoReq getDefaultInstance() {
      return defaultInstance;
    }

    public NSQDemoProtoReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NSQDemoProtoReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sex_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                shopId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000004;
              }
              shopId_.add(input.readInt64());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                shopId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                shopId_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          shopId_ = java.util.Collections.unmodifiableList(shopId_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NSQProtoMsg.internal_static_com_youzan_sz_test_nsq_protobuf_NSQDemoProtoReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NSQProtoMsg.internal_static_com_youzan_sz_test_nsq_protobuf_NSQDemoProtoReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NSQProtoMsg.NSQDemoProtoReq.class, NSQProtoMsg.NSQDemoProtoReq.Builder.class);
    }

    public static com.google.protobuf.Parser<NSQDemoProtoReq> PARSER =
        new com.google.protobuf.AbstractParser<NSQDemoProtoReq>() {
      public NSQDemoProtoReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NSQDemoProtoReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NSQDemoProtoReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SEX_FIELD_NUMBER = 1;
    private int sex_;
    /**
     * <code>required int32 sex = 1;</code>
     */
    public boolean hasSex() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 sex = 1;</code>
     */
    public int getSex() {
      return sex_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SHOPID_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Long> shopId_;
    /**
     * <code>repeated int64 shopId = 3;</code>
     */
    public java.util.List<java.lang.Long>
        getShopIdList() {
      return shopId_;
    }
    /**
     * <code>repeated int64 shopId = 3;</code>
     */
    public int getShopIdCount() {
      return shopId_.size();
    }
    /**
     * <code>repeated int64 shopId = 3;</code>
     */
    public long getShopId(int index) {
      return shopId_.get(index);
    }

    private void initFields() {
      sex_ = 0;
      name_ = "";
      shopId_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, sex_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      for (int i = 0; i < shopId_.size(); i++) {
        output.writeInt64(3, shopId_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sex_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < shopId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(shopId_.get(i));
        }
        size += dataSize;
        size += 1 * getShopIdList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static NSQProtoMsg.NSQDemoProtoReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NSQProtoMsg.NSQDemoProtoReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NSQProtoMsg.NSQDemoProtoReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NSQProtoMsg.NSQDemoProtoReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NSQProtoMsg.NSQDemoProtoReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NSQProtoMsg.NSQDemoProtoReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static NSQProtoMsg.NSQDemoProtoReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static NSQProtoMsg.NSQDemoProtoReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static NSQProtoMsg.NSQDemoProtoReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NSQProtoMsg.NSQDemoProtoReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(NSQProtoMsg.NSQDemoProtoReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code java.nsq.protobuf.NSQDemoProtoReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:java.nsq.protobuf.NSQDemoProtoReq)
        NSQProtoMsg.NSQDemoProtoReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NSQProtoMsg.internal_static_com_youzan_sz_test_nsq_protobuf_NSQDemoProtoReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NSQProtoMsg.internal_static_com_youzan_sz_test_nsq_protobuf_NSQDemoProtoReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NSQProtoMsg.NSQDemoProtoReq.class, NSQProtoMsg.NSQDemoProtoReq.Builder.class);
      }

      // Construct using java.nsq.protobuf.NSQProtoMsg.NSQDemoProtoReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        shopId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NSQProtoMsg.internal_static_com_youzan_sz_test_nsq_protobuf_NSQDemoProtoReq_descriptor;
      }

      public NSQProtoMsg.NSQDemoProtoReq getDefaultInstanceForType() {
        return NSQProtoMsg.NSQDemoProtoReq.getDefaultInstance();
      }

      public NSQProtoMsg.NSQDemoProtoReq build() {
        NSQProtoMsg.NSQDemoProtoReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public NSQProtoMsg.NSQDemoProtoReq buildPartial() {
        NSQProtoMsg.NSQDemoProtoReq result = new NSQProtoMsg.NSQDemoProtoReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sex_ = sex_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          shopId_ = java.util.Collections.unmodifiableList(shopId_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.shopId_ = shopId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NSQProtoMsg.NSQDemoProtoReq) {
          return mergeFrom((NSQProtoMsg.NSQDemoProtoReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NSQProtoMsg.NSQDemoProtoReq other) {
        if (other == NSQProtoMsg.NSQDemoProtoReq.getDefaultInstance()) return this;
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (!other.shopId_.isEmpty()) {
          if (shopId_.isEmpty()) {
            shopId_ = other.shopId_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureShopIdIsMutable();
            shopId_.addAll(other.shopId_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSex()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NSQProtoMsg.NSQDemoProtoReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NSQProtoMsg.NSQDemoProtoReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int sex_ ;
      /**
       * <code>required int32 sex = 1;</code>
       */
      public boolean hasSex() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 sex = 1;</code>
       */
      public int getSex() {
        return sex_;
      }
      /**
       * <code>required int32 sex = 1;</code>
       */
      public Builder setSex(int value) {
        bitField0_ |= 0x00000001;
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sex = 1;</code>
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sex_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Long> shopId_ = java.util.Collections.emptyList();
      private void ensureShopIdIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          shopId_ = new java.util.ArrayList<java.lang.Long>(shopId_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int64 shopId = 3;</code>
       */
      public java.util.List<java.lang.Long>
          getShopIdList() {
        return java.util.Collections.unmodifiableList(shopId_);
      }
      /**
       * <code>repeated int64 shopId = 3;</code>
       */
      public int getShopIdCount() {
        return shopId_.size();
      }
      /**
       * <code>repeated int64 shopId = 3;</code>
       */
      public long getShopId(int index) {
        return shopId_.get(index);
      }
      /**
       * <code>repeated int64 shopId = 3;</code>
       */
      public Builder setShopId(
          int index, long value) {
        ensureShopIdIsMutable();
        shopId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 shopId = 3;</code>
       */
      public Builder addShopId(long value) {
        ensureShopIdIsMutable();
        shopId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 shopId = 3;</code>
       */
      public Builder addAllShopId(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureShopIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, shopId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 shopId = 3;</code>
       */
      public Builder clearShopId() {
        shopId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:java.nsq.protobuf.NSQDemoProtoReq)
    }

    static {
      defaultInstance = new NSQDemoProtoReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:java.nsq.protobuf.NSQDemoProtoReq)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_youzan_sz_test_nsq_protobuf_NSQDemoProtoReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_youzan_sz_test_nsq_protobuf_NSQDemoProtoReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021NSQProtoMsg.proto\022\037com.youzan.sz.test." +
      "nsq.protobuf\"<\n\017NSQDemoProtoReq\022\013\n\003sex\030\001" +
      " \002(\005\022\014\n\004name\030\002 \002(\t\022\016\n\006shopId\030\003 \003(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_youzan_sz_test_nsq_protobuf_NSQDemoProtoReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_youzan_sz_test_nsq_protobuf_NSQDemoProtoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_youzan_sz_test_nsq_protobuf_NSQDemoProtoReq_descriptor,
        new java.lang.String[] { "Sex", "Name", "ShopId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
